// tkey-web/quick-starts/tkey-angular-quick-start/src/app/app.component.ts
import { Component } from "@angular/core";
import { tKey, chainConfig } from './tkey';
import { ShareSerializationModule } from '@tkey/share-serialization';
import { SfaServiceProvider } from '@tkey/service-provider-sfa';
import { WebStorageModule } from '@tkey/web-storage';
import { EthereumPrivateKeyProvider } from "@web3auth/ethereum-provider";
import Web3 from "web3";
import { IProvider } from "@web3auth/base";

// Firebase libraries for custom authentication
import { initializeApp } from "firebase/app";
import { GoogleAuthProvider, getAuth, signInWithPopup, UserCredential } from "firebase/auth";

const verifier = "w3a-firebase-demo";

const ethereumPrivateKeyProvider = new EthereumPrivateKeyProvider({
  config: { chainConfig },
});

// Your web app's Firebase configuration
const firebaseConfig = {
  apiKey: "AIzaSyB0nd9YsPLu-tpdCrsXn8wgsWVAiYEpQ_E",
  authDomain: "web3auth-oauth-logins.firebaseapp.com",
  projectId: "web3auth-oauth-logins",
  storageBucket: "web3auth-oauth-logins.appspot.com",
  messagingSenderId: "461819774167",
  appId: "1:461819774167:web:e74addfb6cc88f3b5b9c92",
};

@Component({
  selector: "app-root",
  templateUrl: "./app.component.html",
  styleUrls: ["./app.component.css"],
})
export class AppComponent {
  title = "Web3Auth tKey Angular Quick Start";
  tKeyInitialised: boolean = false;
  provider: IProvider | null = null;
  loggedIn: boolean = false;
  userInfo: any = null;
  recoveryShare: string = "";
  mnemonicShare: string = "";

  getRecoveryShareInputEvent(event: any) {
    this.recoveryShare = event.target.value;
  }
  getMnemonicShareInputEvent(event: any) {
    this.mnemonicShare = event.target.value;
  }

  app = initializeApp(firebaseConfig);

  signInWithGoogle = async (): Promise<UserCredential> => {
    try {
      const auth = getAuth(this.app);
      const googleProvider = new GoogleAuthProvider();
      const res = await signInWithPopup(auth, googleProvider);
      console.log(res);
      return res;
    } catch (err) {
      console.error(err);
      throw err;
    }
  };

  parseToken = (token: string) => {
    try {
      const base64Url = token.split(".")[1];
      const base64 = base64Url.replace("-", "+").replace("_", "/");
      return JSON.parse(window.atob(base64 || ""));
    } catch (err) {
      console.error(err);
      return null;
    }
  };

  login = async () => {
    try {
      // login with firebase
      const loginRes = await this.signInWithGoogle();
      // get the id token from firebase
      const idToken = await loginRes.user.getIdToken(true);
      this.userInfo = this.parseToken(idToken);

      await (
        tKey.serviceProvider as SfaServiceProvider
      ).connect({
        verifier,
        verifierId: this.userInfo.sub,
        idToken,
      });

      await tKey.initialize();

      this.tKeyInitialised = true;

      var { requiredShares } = tKey.getKeyDetails();

      if (requiredShares > 0) {
        this.uiConsole('Please enter your backup shares, requiredShares:', requiredShares);
      } else {
        await this.reconstructKey();
      }
    }
    catch (err) {
      this.uiConsole(err);
    }
  };

  reconstructKey = async () => {
    try {
      const reconstructedKey = await tKey.reconstructKey();
      const privateKey = reconstructedKey?.secp256k1Key.toString('hex');

      await ethereumPrivateKeyProvider.setupProvider(privateKey);
      this.provider = ethereumPrivateKeyProvider;

      await this.setDeviceShare();
      this.loggedIn = true;
    } catch (e) {
      this.uiConsole(e);
    }
  };

  inputRecoveryShare = async (share: string) => {
    try {
      await tKey.inputShare(share);
      await this.reconstructKey();
      this.uiConsole('Recovery Share Input Successfully');
      return;
    } catch (error) {
      this.uiConsole('Input Recovery Share Error:', error);
    }
  };

  setDeviceShare = async () => {
    try {
      const generateShareResult = await tKey.generateNewShare();
      const share = await tKey.outputShareStore(
        generateShareResult.newShareIndex,
      );
      await (
        tKey.modules["webStorage"] as WebStorageModule
      ).storeDeviceShare(share);
      this.uiConsole('Device Share Set', JSON.stringify(share));
    } catch (error) {
      this.uiConsole('Error', (error as any)?.message.toString(), 'error');
    }
  };

  getDeviceShare = async () => {
    try {
      const share = await (
        tKey.modules["webStorage"] as WebStorageModule
      ).getDeviceShare();

      if (share) {
        this.uiConsole(
          'Device Share Captured Successfully across',
          JSON.stringify(share),
        );
        this.recoveryShare = share.share.share.toString('hex');
        return share;
      }
      this.uiConsole('Device Share Not found');
      return null;
    } catch (error) {
      this.uiConsole('Error', (error as any)?.message.toString(), 'error');
      return null;
    }
  };

  exportMnemonicShare = async () => {
    try {
      const generateShareResult = await tKey.generateNewShare();
      const share = await tKey.outputShareStore(
        generateShareResult.newShareIndex,
      ).share.share;
      const mnemonic = await (
        tKey.modules["shareSerialization"] as ShareSerializationModule
      ).serialize(share, 'mnemonic');
      this.uiConsole(mnemonic);
      return mnemonic;
    } catch (error) {
      this.uiConsole(error);
      return null;
    }
  };

  MnemonicToShareHex = async (mnemonic: string) => {
    if (!tKey) {
      this.uiConsole('tKey not initialized yet');
      return;
    }
    try {
      const share = await (
        tKey.modules["shareSerialization"] as ShareSerializationModule
      ).deserialize(mnemonic, 'mnemonic');
      this.recoveryShare = share.toString("hex");
      return share;
    } catch (error) {
      this.uiConsole(error);
    }
  };

  keyDetails = async () => {
    if (!tKey) {
      this.uiConsole("tKey not initialized yet");
      return;
    }
    const keyDetails = await tKey.getKeyDetails();
    this.uiConsole(keyDetails);
  };

  getUserInfo = async () => {
    this.uiConsole(this.userInfo);
  };

  logout = async () => {
    this.provider = null;
    this.loggedIn = false;
    this.userInfo = null;
    this.uiConsole("logged out");
  };

  getAccounts = async () => {
    if (!this.provider) {
      this.uiConsole("provider not initialized yet");
      return;
    }
    const web3 = new Web3(this.provider as any);

    // Get user's Ethereum public address
    const address = await web3.eth.getAccounts();
    this.uiConsole(address);
  };

  getBalance = async () => {
    if (!this.provider) {
      this.uiConsole("provider not initialized yet");
      return;
    }
    const web3 = new Web3(this.provider as any);

    // Get user's Ethereum public address
    const address = (await web3.eth.getAccounts())[0];

    // Get user's balance in ether
    const balance = web3.utils.fromWei(
      await web3.eth.getBalance(address), // Balance is in wei
      "ether"
    );
    this.uiConsole(balance);
  };

  signMessage = async () => {
    if (!this.provider) {
      this.uiConsole("provider not initialized yet");
      return;
    }
    const web3 = new Web3(this.provider as any);

    // Get user's Ethereum public address
    const fromAddress = (await web3.eth.getAccounts())[0];

    const originalMessage = "YOUR_MESSAGE";

    // Sign the message
    const signedMessage = await web3.eth.personal.sign(
      originalMessage,
      fromAddress,
      "test password!" // configure your own password here.
    );
    this.uiConsole(signedMessage);
  };

  criticalResetAccount = async (): Promise<void> => {
    // This is a critical function that should only be used for testing purposes
    // Resetting your account means clearing all the metadata associated with it from the metadata server
    // The key details will be deleted from our server and you will not be able to recover your account
    if (!this.tKeyInitialised) {
      throw new Error("tKeyInitialised is initialised yet");
    }
    await tKey.storageLayer.setMetadata({
      privKey: tKey.serviceProvider.postboxKey,
      input: { message: "KEY_NOT_FOUND" },
    });
    this.uiConsole('reset');
    this.logout();
  }

  uiConsole(...args: any[]) {
    const el = document.querySelector("#console-ui>p");
    if (el) {
      el.innerHTML = JSON.stringify(args || {}, null, 2);
    }
  }
}

<div class="content">
  <h1 class="title">
    <a target="_blank" href="https://web3auth.io/docs/sdk/core-kit/tkey">Web3Auth tKey</a> Angular
    Quick Start
  </h1>
  <div class="setting">
    <div *ngIf="loggedIn; else elseBlock" class="card-container-account">
      <button class="card card-small" (click)="getUserInfo()">
        Get User Info
      </button>
      <button (click)="keyDetails()" class='card card-small'>
        Key Details
      </button>
      <button (click)="exportMnemonicShare()" class='card card-small'>
        Generate Backup (Mnemonic)
      </button>
      <button class="card card-small" (click)="getAccounts()">
        Get Accounts
      </button>
      <button class="card card-small" (click)="getBalance()">
        Get Balance
      </button>
      <button class="card card-small" (click)="signMessage()">
        Sign Message
      </button>
      <button class="card card-small" (click)="logout()">Log Out</button>
      <button (click)="criticalResetAccount()" class="card card-small">
        [CRITICAL] Reset Account
      </button>
    </div>
    <ng-template #elseBlock>
      <div class="card-container">
        <button class="card card-small" (click)="login()">Login</button>
        <div class="card-container" *ngIf="tKeyInitialised">
          <button (click)="getDeviceShare()" class="card card-small">
            Get Device Share
          </button>
          <label>Backup/ Device Share:</label>
          <input name="recoveryShareInputField" [(ngModel)]="recoveryShare"
            (ngModelChange)="getRecoveryShareInputEvent($event)" class="textfield" />
          <button (click)="inputRecoveryShare(recoveryShare)" class="card card-small">
            Input Recovery Share
          </button>
          <button (click)="criticalResetAccount()" class="card card-small">
            [CRITICAL] Reset Account
          </button>
          <label>Recover Using Mnemonic Share:</label>
          <input name="MnemonicShareInputField" [(ngModel)]="mnemonicShare"
            (ngModelChange)="getMnemonicShareInputEvent($event)" class="textfield" />
          <button (click)="MnemonicToShareHex(mnemonicShare)" class="card card-small">
            Get Recovery Share using Mnemonic
          </button>
        </div>
      </div>
    </ng-template>
    <div class="console" id="console-ui">
      <p class="code">Logged In</p>
    </div>
  </div>
  <footer class="footer">
    <a href="https://github.com/Web3Auth/web3auth-core-kit-examples/tree/main/tkey-web/quick-starts/tkey-angular-quick-start"
      target="_blank" rel="noopener noreferrer">
      Source code
    </a>
  </footer>
</div>

// tkey-web/quick-starts/tkey-nextjs-quick-start/app/page.tsx
/* eslint-disable @typescript-eslint/no-use-before-define */
/* eslint-disable no-console */
/* eslint-disable @typescript-eslint/no-shadow */
"use client";

import { useEffect, useState } from "react";
import { tKey, ethereumPrivateKeyProvider } from './tkey';
import { ShareSerializationModule } from '@tkey/share-serialization';
import { SfaServiceProvider } from '@tkey/service-provider-sfa';
import { WebStorageModule } from '@tkey/web-storage';
import { Web3 } from 'web3';

// Firebase libraries for custom authentication
import { initializeApp } from "firebase/app";
import { GoogleAuthProvider, getAuth, signInWithPopup, UserCredential } from "firebase/auth";

import { IProvider } from "@web3auth/base";

const verifier = "w3a-firebase-demo";

// Your web app's Firebase configuration
const firebaseConfig = {
  apiKey: "AIzaSyB0nd9YsPLu-tpdCrsXn8wgsWVAiYEpQ_E",
  authDomain: "web3auth-oauth-logins.firebaseapp.com",
  projectId: "web3auth-oauth-logins",
  storageBucket: "web3auth-oauth-logins.appspot.com",
  messagingSenderId: "461819774167",
  appId: "1:461819774167:web:e74addfb6cc88f3b5b9c92",
};

function App() {
  const [tKeyInitialised, setTKeyInitialised] = useState(false);
  const [provider, setProvider] = useState<IProvider | null>(null);
  const [loggedIn, setLoggedIn] = useState(false);
  const [userInfo, setUserInfo] = useState({});
  const [recoveryShare, setRecoveryShare] = useState<string>("");
  const [mnemonicShare, setMnemonicShare] = useState<string>("");

  // Firebase Initialisation
  const app = initializeApp(firebaseConfig);

  const signInWithGoogle = async (): Promise<UserCredential> => {
    try {
      const auth = getAuth(app);
      const googleProvider = new GoogleAuthProvider();
      const res = await signInWithPopup(auth, googleProvider);
      console.log(res);
      return res;
    } catch (err) {
      console.error(err);
      throw err;
    }
  };

  const parseToken = (token: string) => {
    try {
      const base64Url = token.split(".")[1];
      const base64 = base64Url.replace("-", "+").replace("_", "/");
      return JSON.parse(window.atob(base64 || ""));
    } catch (err) {
      console.error(err);
      return null;
    }
  };

  const login = async () => {
    try {
      // login with firebase
      const loginRes = await signInWithGoogle();
      // get the id token from firebase
      const idToken = await loginRes.user.getIdToken(true);
      const userInfo = parseToken(idToken);
      setUserInfo(userInfo);

      await (
        tKey.serviceProvider as SfaServiceProvider
      ).connect({
        verifier,
        verifierId: userInfo.sub,
        idToken,
      });

      await tKey.initialize();

      setTKeyInitialised(true);

      var { requiredShares } = tKey.getKeyDetails();

      if (requiredShares > 0) {
        uiConsole('Please enter your backup shares, requiredShares:', requiredShares);
      } else {
        await reconstructKey();
      }
    }
    catch (err) {
      uiConsole(err);
    }
  };

  const reconstructKey = async () => {
    try {
      const reconstructedKey = await tKey.reconstructKey();
      const privateKey = reconstructedKey?.secp256k1Key.toString('hex');

      await ethereumPrivateKeyProvider.setupProvider(privateKey);
      setProvider(ethereumPrivateKeyProvider);
      await setDeviceShare();
      setLoggedIn(true);
    } catch (e) {
      uiConsole(e);
    }
  };

  const inputRecoveryShare = async (share: string) => {
    try {
      await tKey.inputShare(share);
      await reconstructKey();
      uiConsole('Recovery Share Input Successfully');
      return;
    } catch (error) {
      uiConsole('Input Recovery Share Error:', error);
    }
  };

  const keyDetails = async () => {
    if (!tKey) {
      uiConsole("tKey not initialized yet");
      return;
    }
    const keyDetails = await tKey.getKeyDetails();
    uiConsole(keyDetails);
  };

  const setDeviceShare = async () => {
    try {
      const generateShareResult = await tKey.generateNewShare();
      const share = await tKey.outputShareStore(
        generateShareResult.newShareIndex,
      );
      await (
        tKey.modules.webStorage as WebStorageModule
      ).storeDeviceShare(share);
      uiConsole('Device Share Set', JSON.stringify(share));
    } catch (error) {
      uiConsole('Error', (error as any)?.message.toString(), 'error');
    }
  };

  const getDeviceShare = async () => {
    try {
      const share = await (
        tKey.modules.webStorage as WebStorageModule
      ).getDeviceShare();

      if (share) {
        uiConsole(
          'Device Share Captured Successfully across',
          JSON.stringify(share),
        );
        setRecoveryShare(share.share.share.toString('hex'));
        return share;
      }
      uiConsole('Device Share Not found');
      return null;
    } catch (error) {
      uiConsole('Error', (error as any)?.message.toString(), 'error');
    }
  };

  const exportMnemonicShare = async () => {
    try {
      const generateShareResult = await tKey.generateNewShare();
      const share = await tKey.outputShareStore(
        generateShareResult.newShareIndex,
      ).share.share;
      const mnemonic = await (
        tKey.modules.shareSerialization as ShareSerializationModule
      ).serialize(share, 'mnemonic');
      uiConsole(mnemonic);
      return mnemonic;
    } catch (error) {
      uiConsole(error);
    }
  };

  const MnemonicToShareHex = async (mnemonic: string) => {
    if (!tKey) {
      uiConsole('tKey not initialized yet');
      return;
    }
    try {
      const share = await (
        tKey.modules.shareSerialization as ShareSerializationModule
      ).deserialize(mnemonic, 'mnemonic');
      setRecoveryShare(share.toString("hex"));
      return share;
    } catch (error) {
      uiConsole(error);
    }
  };

  const getUserInfo = async () => {
    uiConsole(userInfo);
  };

  const logout = async () => {
    setProvider(null);
    setLoggedIn(false);
    setUserInfo({});
    uiConsole("logged out");
  };

  const getAccounts = async () => {
    if (!provider) {
      uiConsole("provider not initialized yet");
      return;
    }
    const web3 = new Web3(provider as any);

    // Get user's Ethereum public address
    const address = await web3.eth.getAccounts();
    uiConsole(address);
  };

  const getBalance = async () => {
    if (!provider) {
      uiConsole("provider not initialized yet");
      return;
    }
    const web3 = new Web3(provider as any);

    // Get user's Ethereum public address
    const address = (await web3.eth.getAccounts())[0];

    // Get user's balance in ether
    const balance = web3.utils.fromWei(
      await web3.eth.getBalance(address), // Balance is in wei
      "ether"
    );
    uiConsole(balance);
  };

  const signMessage = async () => {
    if (!provider) {
      uiConsole("provider not initialized yet");
      return;
    }
    const web3 = new Web3(provider as any);

    // Get user's Ethereum public address
    const fromAddress = (await web3.eth.getAccounts())[0];

    const originalMessage = "YOUR_MESSAGE";

    // Sign the message
    const signedMessage = await web3.eth.personal.sign(
      originalMessage,
      fromAddress,
      "test password!" // configure your own password here.
    );
    uiConsole(signedMessage);
  };

  const criticalResetAccount = async (): Promise<void> => {
    // This is a critical function that should only be used for testing purposes
    // Resetting your account means clearing all the metadata associated with it from the metadata server
    // The key details will be deleted from our server and you will not be able to recover your account
    if (!tKeyInitialised) {
      throw new Error("tKeyInitialised is initialised yet");
    }
    await tKey.storageLayer.setMetadata({
      privKey: tKey.serviceProvider.postboxKey,
      input: { message: "KEY_NOT_FOUND" },
    });
    uiConsole('reset');
    logout();
  }


  function uiConsole(...args: any[]): void {
    const el = document.querySelector("#console>p");
    if (el) {
      el.innerHTML = JSON.stringify(args || {}, null, 2);
    }
    console.log(...args);
  }

  const loggedInView = (
    <>
      <div className="flex-container">
        <div>
          <button onClick={getUserInfo} className="card">
            Get User Info
          </button>
        </div>
        <div>
          <button onClick={keyDetails} className='card'>
            Key Details
          </button>
        </div>
        <div>
          <button onClick={exportMnemonicShare} className='card'>
            Generate Backup (Mnemonic)
          </button>
        </div>
        <div>
          <button onClick={getAccounts} className="card">
            Get Accounts
          </button>
        </div>
        <div>
          <button onClick={getBalance} className="card">
            Get Balance
          </button>
        </div>
        <div>
          <button onClick={signMessage} className="card">
            Sign Message
          </button>
        </div>
        <div>
          <button onClick={logout} className="card">
            Log Out
          </button>
        </div>
        <div>
          <button onClick={criticalResetAccount} className="card">
            [CRITICAL] Reset Account
          </button>
        </div>
      </div>
    </>
  );

  const unloggedInView = (
    <>
      <button onClick={login} className="card">
        Login
      </button>
      <div className={tKeyInitialised ? "" : "disabledDiv"} >

        <button onClick={() => getDeviceShare()} className="card">
          Get Device Share
        </button>
        <label>Backup/ Device Share:</label>
        <input value={recoveryShare} onChange={(e) => setRecoveryShare(e.target.value)}></input>
        <button onClick={() => inputRecoveryShare(recoveryShare)} className="card">
          Input Recovery Share
        </button>
        <button onClick={criticalResetAccount} className="card">
          [CRITICAL] Reset Account
        </button>
        <label>Recover Using Mnemonic Share:</label>
        <input value={mnemonicShare} onChange={(e) => setMnemonicShare(e.target.value)}></input>
        <button onClick={() => MnemonicToShareHex(mnemonicShare)} className="card">
          Get Recovery Share using Mnemonic
        </button>
      </div>
    </>
  );

  return (
    <div className="container">
      <h1 className="title">
        <a target="_blank" href="https://web3auth.io/docs/sdk/core-kit/tkey" rel="noreferrer">
          Web3Auth tKey
        </a>{" "}
        & NextJS Quick Start
      </h1>

      <div className="grid">{loggedIn ? loggedInView : unloggedInView}</div>
      <div id="console" style={{ whiteSpace: "pre-line" }}>
        <p style={{ whiteSpace: "pre-line" }}></p>
      </div>

      <footer className="footer">
        <a
          href="https://github.com/Web3Auth/web3auth-core-kit-examples/tree/main/tkey-web/quick-starts/tkey-nextjs-quick-start"
          target="_blank"
          rel="noopener noreferrer"
        >
          Source code
        </a>
      </footer>
    </div>
  );
}

export default App;
